env: "dev"

auth:
  client_id: "42c18af9-b3e1-4bc9-ac0a-f480e2eeed74"
  client_secret: "tE6DzdPz32jZ44ci5S7iIq25DSSjMQFMrWvi8S6LyTMwDPjBMrFmb2N9LSG9wPpz"
  redirect_uri: "https://grubworm-possible-midge.ngrok-free.app/"

http_server:
  address: ":8080"

grpc:
  port: "50051"

mysql:
  DB_HOST: "localhost" #Обратите внимание, что если вы используете код из docker, вам нужно вызвать контейнер из порта операционной системы, и в нашей #ситуации вы должны вызвать localhost
#  DB_HOST: "fullstack-mysql"
  DB_DRIVER: "mysql"
  API_SECRET: "98hbun98h"                          # Используется для создания JWT. Может быть что угодно
  DB_USER: "dmiroshnikov"
  DB_PASSWORD: "111"
  DB_NAME: "fullstack_api"
  DB_PORT: 3306
  # Mysql Test
  TEST_DB_HOST: "mysql_test"
  # TEST_DB_HOST=127.0.0.1                       #При запуске приложения без docker
  TEST_DB_DRIVER: "mysql"
  TEST_API_SECRET: "98hbun98h"
  TEST_DB_USER: "dmiroshnikov"
  TEST_DB_PASSWORD: "111"
  TEST_DB_NAME: "fullstack_api_test"
  TEST_DB_PORT: 3306